# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: check-yaml

- repo: https://github.com/kynan/nbstripout
  rev: 0.5.0
  hooks:
    - id: nbstripout

- repo: https://github.com/asottile/pyupgrade
  rev: v2.26.0
  hooks:
    - id: pyupgrade
      args: [--py36-plus]

- repo: https://github.com/ambv/black
  rev: 21.7b0
  hooks:
    - id: black
      language_version: python3

# - repo: https://github.com/nbQA-dev/nbQA
#   rev: 0.3.5
#   hooks:
#     - id: nbqa-pyupgrade
#       args: [--nbqa-mutate]
#     - id: nbqa-black
#       args: [--nbqa-mutate]
#     - id: nbqa-isort
#       args: [--nbqa-mutate]
#     - id: nbqa-flake8

- repo: https://github.com/pre-commit/mirrors-isort
  rev: 'v5.9.3'
  hooks:
    - id: isort
      args: ["--profile", "black"]

- repo: https://github.com/hadialqattan/pycln
  rev: v1.0.3 # Possible releases: https://github.com/hadialqattan/pycln/tags
  hooks:
    - id: pycln
      args: [--config=pyproject.toml]