version: '3.7'
services:
  neo4j:
    image: neo4j:4.4
    restart: always
    # hostname: neo4j-yt
    # container_name: neo4j-yt-release
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
       - $HOME/.yourtube/neo4j/data:/data
    environment:
      NEO4J_AUTH: neo4j/yourtube

  yourtube:
    image: filyp/yourtube:latest
    # container_name: yourtube-release
    # hostname: yourtube
    # restart: always
    depends_on:
        - neo4j
    volumes:
      - $HOME/.yourtube/data:/yourtube/data
    ports:
      - "8866:8866"
