name: release

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install poetry
      run: |
        curl -fsS -o get-poetry.py https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py
        python get-poetry.py -y
    - name: Install project dependencies
      run: |
        source $HOME/.poetry/env
        poetry install
    - name: Test with pytest
      run: |
        source $HOME/.poetry/env
        poetry run pytest -s .
    - name: Publish
      run: |
        source $HOME/.poetry/env
        poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
        poetry publish --build
